### ISSUE TITLE
rpc package tests broken with "not a subtype" errors in 2.2+

### ISSUE THREAD

**Issue by jcollins-g** [dart-archive/rpc#133]
See dart-lang/sdk#35009.

**Comment by supermuka** [comment]
Uff.. I was thinking that it was doing something wrong! 

Using _rpc 0.6.0_ with _sdk 2.1.0-dev.8.0_ , in my code is thrown the following error:

> Field `members` has wrong type: type `'List<dynamic>'` is not a subtype of type `'List<UserBase>'` of 'value'

With _sdk 2.0.0_ it works.

**Comment by jcollins-g** [comment]
@supermuka I suggest reverting to 2.1.0-dev.7.1 (that seems to still have the good behavior) if you need the 2.1 branch.  Hopefully the referenced SDK bug is getting enough attention, I'll keep advocating for it.  At the very least, if the rpc package itself is doing something wrong we need to know what it is so we can change it.

**Comment by jcollins-g** [comment]
Investigation in dart-lang/sdk#35009 revealed a way out for the rpc package: a refactor changing how the rpc package instantiates objects for clients to take into account their types with the mirror system.  (A sample of some of the work required is in https://github.com/dart-lang/rpc/compare/experimental-mirrors-refactor).

**Comment by supermuka** [comment]
Just a thought, without depth: maybe it could be an alternative to make a refactory of the rpc package by changing the method for serialization, from mirror to code generated as a json_serialization (https://pub.dartlang.org/packages/json_serializable) does.

**Comment by jcollins-g** [comment]
@supermuka It's certainly possible, though at that point I might look to a transition to grpc for my project (dart-services, the DartPad backend) rather than redesigning this package.  grpc already uses generated code -- watching the rest of the dart ecosystem that seems to be the way folks are heading.

**Comment by jcollins-g** [comment]
@supermuka Just to let you know, we've decided to ship a version of rpc with a more complete fix for this, since the mirrors change is going to go into a future version of 2.1 stable.  I'll try and get a PR set up for this in the next day or so and if you'd like I'd appreciate your feedback on it as a fellow customer of the package.

**Comment by supermuka** [comment]
@jcollins-g, I tested and it works fine now, including generic problem https://github.com/dart-archive/rpc/issues/134, using the branch `experimental-mirrors-refactor` and Dart version 2.1.1-dev.1.0.
