### ISSUE TITLE
Add parsing for all object with serializable object or list of serializable object

### ISSUE THREAD

**Issue by maximepvrt** [dart-archive/rpc#51]

**Comment by wibling** [comment]
Hi Maxime,

Could you elaborate a bit with an example?

Regards,
/gustav

**Comment by maximepvrt** [comment]
currently it's impossible to return this item :)

```dart
class Account {
  int id;
  String mail;
  User me;
  List<User> family;
  Account(this.mail) : super();
}

class User {
  int id;
  String firstName;
  String lastName;
  User(this.firstName, this.lastName) : super();
}
```

**Comment by maximepvrt** [comment]
@wibling ?

**Comment by wibling** [comment]
Hi Maxime,

Sorry for the long delay. I have been busy with other (unrelated) work.
For you example above it should work as is. I just tried it out by modifying the example/toyapi.dart file to also have a method that returns an Account as you describe it.

Take a look at: 

https://codereview.chromium.org/1226373002/diff/1/example/toyapi.dart

If I call the new 'account' method by doing a 

GET http://localhost:8080/api/toyApi/0.1/account

I get back the response:

{
 "mail": "john@doe.com",
 "family": [
  {
   "firstName": "John",
   "lastName": "Doe"
  }
 ]
}

**Comment by FaisalAbid** [comment]
Hey @maximepvrt did that solve your issue?
